debug = true
mode = "Firestore"

[apiserver]
application_url = "localhost:80"
hostname = "localhost"
allow_origin = "http://localhost:3000"
api_key = "dev-api-key-12345"

[firestore_config]
project_id = "urlshortener-445813"